apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-rhcs-rosa-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-rhcs-rosa-test
    app.kubernetes.io/part-of: terraform-rhcs-rosa-test
  name: terraform-rhcs-rosa-test
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: terraform-rhcs-rosa-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: terraform-rhcs-rosa-test
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/terraform-rhcs-rosa-test/terraform-rhcs-rosa-test@sha256:65bb9c1f1ef1dfd16ddede7f4f217a41d5545d3c9f016afeb5b8528d254b39c8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
