apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-rhcs-rosa-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-rhcs-rosa-test
    app.kubernetes.io/part-of: terraform-rhcs-rosa-test
  name: terraform-rhcs-rosa-test
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: terraform-rhcs-rosa-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: terraform-rhcs-rosa-test
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/terraform-provider-rhcs/terraform-rhcs-rosa-test@sha256:0287f74d19e3000878fc35abf39f4912bb19cef86db933a3c4d64db4e03a1411
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
