apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-rhcs-rosa-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-rhcs-rosa-test
    app.kubernetes.io/part-of: terraform-rhcs-rosa-test
  name: terraform-rhcs-rosa-testfvq3
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: terraform-rhcs-rosa-test
    weight: 100
status: {}
